### ISSUE TITLE
a few suggestions for tablet optimization

### ISSUE THREAD

**Issue by furkanunluturkk** [tuyafeng/Via#622]
i don't know if these feature can be implemented but i just wanted to note them.
* bar view for tabs
* keyboard shortcuts (CTRL+Tab, ALT+1,2,3,4... - especially for quitting the app)
"tab restoring" doesn't work on tablets. if there was a shortcut in place of the "quit" button in the phone version, that'd be awesome.
NOTE: there could be a feature like "closing the all tabs closes the Via", as in Brave browser.

Via really rocks, and i don't want to use any other browser just even for the sake of the option/feature of "permanent incognito".

**Comment by tuyafeng** [comment]
Keyboard shortcuts are already supported. I have added support for almost all Chrome shortcuts, such as ctrl + t to create a new tab, ctrl + tab to switch tabs and so on. The tabs display should indeed be optimized, and I will gradually improve it. thank you for your support.

**Comment by tuyafeng** [comment]
Sorry, I just added a shortcut key to the code. After testing, I found that the shortcut key will only take effect after the edittext has the focus, that is, only when you enter the URL, such as ctrl t, these shortcut keys will take effect. Because the underlying code of android is designed like this, I also feel very confused. All in all, it seems that we need to wait for Google to perfect the keyboard adaptation.
