### ISSUE TITLE
[NewFeatureRequest] "Trash Can" feature to quickly reopen recently closed tab

### ISSUE THREAD

**Issue by himawansyahputro** [tuyafeng/Via#666]
To prevent Accidentally closing tabs that we didn’t meant to

Just like what Vivaldi Browser have

https://www.google.com/amp/s/www.hongkiat.com/blog/cool-vivaldi-browser-features/amp/

**Comment by oris1024** [comment]
Also wanted to suggest this. This would help when i accidently close a tab that has back history that i still need (instead of going back to needed previous pages). Because the tab's previous pages, in my usage can be *very* old - i simply do not find them through history.
For this to work, when a recently closed tab is restored, it would have to be restored with its back(and forward?) history.

Given the current interface, i think, this would fit either:
- as a fourth tab in the Bookmarks/History/Saved screen
- or, as a sub-tab (or some kind of toggle control) under the History tab of the above-mentioned screen.

Good wishes

**Comment by oris1024** [comment]
This is now implemented! As of version 5.2.0. Even tab (back) history is restored.

I thank the developer for this 🙏, and suggest marking this issue as closed/completed.
