### ISSUE TITLE
Custom filters not working

### ISSUE THREAD

**Issue by K1DV5** [tuyafeng/Via#869]
Sorry I'm opening a separate issue, but the other issue I saw was about subdomains and not my question. I wanted to block certain types of assets from all pages like fonts and media. I tried `*$font,media` and that doesn't work. I tried it with images like `*$image`, still didn't work. Then I tried a filter as simple as `google.com` but nothing was blocked when I was expecting an error like BLOCKED_BY_CLIENT or something. Am I doing something wrong?

**Comment by Krishna-verma** [comment]
Few things to confirm with your issue:

- Check if your ***Ad blocking**** is actually on.
- Check if your custom filter complies with ABP filter rules.

**Comment by K1DV5** [comment]
Both the things you mentioned were ok. But I was looking through the other issues and I saw that custom filters require JavaScript to be enabled. I enabled it and tried some filters and they worked. But I still have trouble blocking some parts of all urls, like all fonts. I tried `*$font` and some others but nothing. Is there no pattern that matches all URLs?

**Comment by Krishna-verma** [comment]
I'm not sure if you're using a correct syntax but here I've got something for you.
If you really want to block those fonts, this might help you.
https://fanboy.co.nz/fanboy-antifonts.txt
But still some fonts might be able to load since there are more than one way to implement external font on a website.

**Comment by Krishna-verma** [comment]
Alternatively, you can just use this:
*$font,third-party

**Comment by tuyafeng** [comment]
Via’s custom filter is slightly different from ABP. The rule you wrote cannot be applied in Via because it cannot be loaded. Via’s custom filter needs a key to match the url. Via uses 5 consecutive characters in the filter as the key. Only when the filter is matched first will the url resource type be judged. The reason for this design is to achieve fast matching on the mobile phone. If you want to block all fonts, you can use filters like `.ttf?` (I actually don't recommend this because it may cause some web pages to display abnormally).

**Comment by K1DV5** [comment]
Alright, and thank you for the explanation.
